# LM Studio Context Size Benchmark Configuration

# API Settings
api:
  url: "http://localhost:5002"
  timeout: 3600  # seconds
  delay_between_requests: 2  # seconds
  delay_between_models: 10  # seconds

# System Information
system:
  name: "M3 Max MacBook Pro 128GB RAM"
  notes: "MXFP4 quantization"

# Models to test (in order) - 3 GPT-OSS 120B variants
models:
  - name: "openai/gpt-oss-120b"
    enabled: true
    description: "GPT-OSS 120B MXFP4 (OpenAI)"
    
  - name: "mlx-community/gpt-oss-120b"
    enabled: true
    description: "GPT-OSS 120B MXFP4 (MLX Community)"

  - name: "qwen/qwen3-next-80b"
    enabled: true
    description: "Qwen3 Next 80B (MLX)"

# Test Configuration
test:
  # Context sizes to test (in tokens) - Quick experiment up to 20k
  context_sizes: [128, 512, 1024, 4096, 16384, 32768, 65536]
  
  # Alternative: Use range instead of explicit list
  # context_range:
  #   start: 10000
  #   end: 100000
  #   step: 10000
  
  # Number of completion tokens to generate for each test
  max_tokens: 512
  
  # Temperature for generation
  temperature: 0.1
  
  # Number of measurements per context size (results are averaged)
  trials_per_context: 3

  # When averaging, randomize each trial's prompt so KV cache can't short-cut
  unique_trial_prompts: true

  # Disable server-side prompt caching between requests (if supported)
  disable_prompt_cache: true

# Book content settings
content:
  book_path: "books/alice_adventures_in_wonderland.txt"
  # Prompt types to use (random selection)
  prompt_types:
    - "literary_analysis"
    - "creative_writing_feedback" 
    - "editorial_review"
    - "lecture_preparation"
    - "adaptation_analysis"

# Output settings
output:
  results_dir: "results"
  create_charts: true
  save_summary: true
  
# Chart settings
charts:
  dpi: 300
  figure_size: [16, 8]  # width, height in inches
  colors:
    "openai/gpt-oss-120b": "#8FD694"        # Mint green
    "mlx-community/gpt-oss-120b": "#F28E8E"  # Soft coral
    "qwen/qwen3-next-80b": "#6FA8DC"        # Cornflower blue
    "default": "#77B6EA"                    # Light sky blue
